name: Docker image build defaults
description: |
    Defaults for building docker images

inputs:
    username:
        description: "Docker repo username"
        required: false
        default: ""
    password:
        description: "Docker repo password"
        required: false
        default: ""
    registry:
        description: "Docker Registry"
        required: false
        default: "docker.io"

outputs:
  # branch_name:
  #   description: "The branch name (default: null)"
  #   value: ${{ steps.set_vars.outputs.branch_name }}
  # github_sha_short:
  #   description: "The short SHA of the commit (default: null)"
  #   value: ${{ steps.set_vars.outputs.github_sha_short }}
  # github_ref_short:
  #   description: "The short ref of the commit (default: null)"
  #   value: ${{ steps.set_vars.outputs.github_ref_short }}
  docker_push:
    description: "True if the branch is a release (default: false)"
    value: ${{ steps.set_vars.outputs.docker_push }}

runs:
    using: "composite"
    steps:
        ## Set some vars to be used in the build process
        - name: Set Vars
          id: set_vars
          shell: bash
          run: |
              # event=${{ github.event_name }}
              # case ${event} in
              #   pull_request|pull_request_target|pull_request_review)
              #     echo "[PR]: true"
              #     branch=${{ github.event.pull_request.head.ref }}
              #     ;;
              #   *)
              #     echo "[PR]: false"
              #     branch=${GITHUB_REF#refs/heads/}
              #     ;;
              # esac
              # echo "BRANCH_NAME=$branch" >> $GITHUB_ENV
              # echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
              # echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
              # echo "DOCKER_PUSH=${{ (inputs.username != '') && (inputs.password != '') }}" >> $GITHUB_ENV

              # echo "branch_name=$branch" >> $GITHUB_OUTPUT
              # echo "github_sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
              # echo "github_ref_short=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
              echo "docker_push=${{ (inputs.username != '') && (inputs.password != '') }}" >> $GITHUB_OUTPUT

        ## Setup QEMU for multi-arch builds
        - name: Set up QEMU
          uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
          with:
              cache-image: false # don't cache the binfmt image

        ## Setup docker buildx
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
          with:
              cache-binary: false

        ## Login to docker registry
        - name: Docker Login
          if: |
              inputs.username != '' &&
              inputs.password != ''
          uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
          with:
              registry: ${{ inputs.registry }}
              username: ${{ inputs.username }}
              password: ${{ inputs.password }}
              logout: true
