FROM alpine AS builder
# Use a small image to download and extract the release archive

ARG TAG
ARG BIN_ARCH
ARG BUILDPLATFORM
ARG TARGETARCH
ARG TARGETVARIANT
ARG REPO

RUN case ${TARGETPLATFORM} in \
    linux/amd64*) BIN_ARCH=linux-musl-x64 ;; \
    linux/arm64*) BIN_ARCH=linux-musl-arm64 ;; \
    *) exit 1 ;; \
    esac \
    && echo "BIN_ARCH: $BIN_ARCH" \
    && echo "wget -q https://github.com/${REPO}/releases/download/${TAG}/${BIN_ARCH}.zip -O /${BIN_ARCH}.zip" \
    && wget -q https://github.com/${REPO}/releases/download/${TAG}/${BIN_ARCH}.zip -O /${BIN_ARCH}.zip \
    && unzip ${BIN_ARCH}.zip -d /out

FROM alpine
COPY --from=builder /out/* /bin/
ARG TAG

RUN case "${TAG}" in \
        signer-*) \
            echo "/bin/stacks-signer run --config /signer-config.toml" > /tmp/command.sh \
            ;; \
        *) \
            echo "/bin/stacks-node mainnet" > /tmp/command.sh && \
            rm /bin/stacks-cli /bin/clarity-cli /bin/stacks-inspect \
            ;; \
    esac && \
    chmod +x /tmp/command.sh

CMD ["sh", "-c", "/tmp/command.sh"]
