FROM --platform=${TARGETPLATFORM} alpine as builder
# Use a small image to download and extract the release archive

ARG TAG
ARG BIN_ARCH
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETARCH
ARG TARGETVARIANT
ARG REPO

RUN case ${TARGETPLATFORM} in \
    linux/amd64*) BIN_ARCH=linux-glibc-x64 ;; \
    linux/arm64*) BIN_ARCH=linux-glibc-arm64 ;; \
    *) exit 1 ;; \
    esac
RUN echo "TARGETPLATFORM: $TARGETPLATFORM" \
    && echo "BIN_ARCH: $BIN_ARCH" \
    && echo "ARTIFACT: ./release/${BIN_ARCH}.zip"

COPY ./release/${BIN_ARCH}.zip .

RUN unzip "${BIN_ARCH}.zip" "stacks-node" -d "/out"

FROM --platform=${TARGETPLATFORM} debian:bookworm
COPY --from=builder /out/* /bin/
CMD ["/bin/stacks-node mainnet"]
