## Composite action to check if the branch is a release tag or not
name: Check Release
description: |
  Checks if the branch is a release tag and sets output variables accordingly.

inputs:
  tag:
    description: "The branch name against which the step runs"
    required: true

outputs:
  node_tag:
    description: "The node release tag, if there is one (empty otherwise)."
    value: ${{ steps.check_release.outputs.node_tag }}
  node_docker_tag:
    description: "The node release tag for docker, if there is one (empty otherwise)."
    value: ${{ steps.check_release.outputs.node_docker_tag }}
  signer_tag:
    description: "The signer release tag, if there is one (empty otherwise)."
    value: ${{ steps.check_release.outputs.signer_tag }}
  signer_docker_tag:
    description: "The signer release tag for docker, if there is one (empty otherwise)."
    value: ${{ steps.check_release.outputs.signer_docker_tag }}
  is_node_release:
    description: "True if the branch is a release one, false otherwise."
    value: ${{ steps.check_release.outputs.is_node_release }}
  is_signer_release:
    description: "True if the branch is a release one, false otherwise."
    value: ${{ steps.check_release.outputs.is_signer_release }}

runs:
  using: "composite"
  steps:
    - name: Checkout the latest code
      id: git_checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: Set Release Outputs
      id: check_release
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
      run: bash ./.github/scripts/check_release.sh
