name: Changelog Check
description: |
  Checks for changelog fragments in pull requests.

runs:
  using: "composite"
  steps:
    - name: Check for changelog fragments
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const changelog = require('./.github/scripts/changelog.js');
          await changelog({ github, context, core });
