FROM rust:bullseye as build

ARG STACKS_NODE_VERSION="No Version Info"
ARG GIT_BRANCH='No Branch Info'
ARG GIT_COMMIT='No Commit Info'
ARG BUILD_DIR=/build
ARG OSXCROSS="https://github.com/hirosystems/docker-osxcross-rust/releases/download/MacOSX12.0.sdk/osxcross-d904031_MacOSX12.0.sdk.tar.zst"
ARG TARGET=aarch64-apple-darwin
ARG TAG
WORKDIR /src

COPY . .

RUN apt-get update && apt-get install -y clang zstd

# Retrieve and install osxcross 
RUN wget -nc -O /tmp/osxcross.tar.zst ${OSXCROSS} \
    && mkdir -p /opt/osxcross && tar -xaf /tmp/osxcross.tar.zst -C /opt/osxcross

# Run all the build steps in ramdisk in an attempt to improve build time
RUN --mount=type=tmpfs,target=${BUILD_DIR} cp -R /src/. ${BUILD_DIR}/ \
    && cd ${BUILD_DIR} \
    && rustup target add ${TARGET} \
    && . /opt/osxcross/env-macos-aarch64 \
    && case "${TAG}" in \
        signer-*) \
            BUILD_ARG="--bin stacks-signer" \
            ;; \
        *) \
            BUILD_ARG="" \
            ;; \
    esac \
    && cargo build --features monitoring_prom,slog_json --release --workspace --target ${TARGET} ${BUILD_ARG} \
    # Conditionally rebuild `stacks-signer` if GIT_BRANCH does NOT contain "signer"
    && if echo "${GIT_BRANCH}" | grep -vq "signer"; then \
        STACKS_NODE_VERSION="${STACKS_NODE_VERSION}.0"; \
        cargo build --features monitoring_prom,slog_json --release --workspace --target ${TARGET} --bin stacks-signer; \
    fi \
    # End conditional
    && mkdir -p /out \
    && find ${BUILD_DIR}/target/${TARGET}/release/ -maxdepth 1 -executable -type f | xargs cp -at /out/ 

FROM scratch AS export-stage
COPY --from=build /out/* /
