FROM rust:bookworm as build

ARG STACKS_NODE_VERSION="No Version Info"
ARG GIT_BRANCH='No Branch Info'
ARG GIT_COMMIT='No Commit Info'
ARG BUILD_DIR=/build
ARG TARGET=x86_64-pc-windows-gnu
ARG TARGET_CPU
ENV RUSTFLAGS="${TARGET_CPU:+${RUSTFLAGS} -Ctarget-cpu=${TARGET_CPU}}"
ARG TAG
WORKDIR /src

COPY . .

RUN apt-get update && apt-get install -y git gcc-mingw-w64-x86-64 libclang-dev

# Run all the build steps in ramdisk in an attempt to improve build time
RUN --mount=type=tmpfs,target=${BUILD_DIR} cp -R /src/. ${BUILD_DIR}/ \
    && cd ${BUILD_DIR} \
    && rustup target add ${TARGET} \
    && case "${TAG}" in \
        signer-*) \
            BUILD_ARG="--bin stacks-signer" \
            ;; \
        *) \
            BUILD_ARG="" \
            ;; \
    esac \
    && export CC_x86_64_pc_windows_gnu=x86_64-w64-mingw32-gcc \
    && export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=x86_64-w64-mingw32-gcc \
    && cargo build --features monitoring_prom,slog_json --release --workspace --target ${TARGET} ${BUILD_ARG} \
    # Conditionally rebuild `stacks-signer` if GIT_BRANCH does NOT contain "signer"
    && if echo "${GIT_BRANCH}" | grep -vq "signer"; then \
        STACKS_NODE_VERSION="${STACKS_NODE_VERSION}.0"; \
        cargo build --features monitoring_prom,slog_json --release --workspace --target ${TARGET} --bin stacks-signer; \
    fi \
    # End conditional
    && mkdir -p /out \
    && find ${BUILD_DIR}/target/${TARGET}/release/ -maxdepth 1 -executable -type f | xargs cp -at /out/

FROM scratch AS export-stage
COPY --from=build /out/* /
