## Perform Clippy checks - currently set to defaults
##   https://github.com/rust-lang/rust-clippy#usage
##   https://rust-lang.github.io/rust-clippy/master/index.html
##
name: Clippy Checks

# Only run when:
#   - PRs are (re)opened against develop branch
on:
  workflow_dispatch:
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

concurrency:
  group: clippy-${{ github.head_ref || github.ref || github.run_id }}
  ## Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  clippy-checks:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      # - uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      #   with:
      #     egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Setup Rust Toolchain
        uses: ./.github/actions/setup-rust-toolchain
        with:
          components: clippy

      - name: Clippy
        run: cargo clippy-stacks

      - name: Clippy Stackslib
        run: cargo clippy-stackslib
