name: Constants Check

# Only run when:
#   - PRs are (re)opened against develop branch
on:
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  check-consts:
    name: Check the constants from stacks-inspect
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Setup Rust Toolchain
        uses: ./.github/actions/setup-rust-toolchain

      - name: Dump constants JSON
        run: |
          cargo run --bin stacks-inspect -- dump-consts | tee out.json

      ## output any diff to the github job summary
      - name: Compare expected constants JSON
        run: |
          diff out.json ./sample/expected_consts.json >> $GITHUB_STEP_SUMMARY
