## Github workflow to create reusable caches

name: TEST Release workflow

on:
  push:
    branches:
      - fix/release_workflow
  workflow_dispatch:
  pull_request:

concurrency:
  group: github-release-${{ github.head_ref || github.ref }}
  ## Always cancel duplicate jobs
  cancel-in-progress: true

run-name: test release build matrix

jobs:
  ## Build arch dependent binaries from source
  ##
  ## Runs when the following is true:
  ##  - either node or signer tag is provided
  build-binaries:
    name: Build Binaries
    strategy:
      ## Run a maximum of 10 builds concurrently, using the matrix defined in inputs.arch
      max-parallel: 10
      matrix:
        arch:
          - linux-musl
          - linux-glibc
          - macos
          - windows
        cpu:
          - arm64
          - x86-64 ## defaults to x86-64-v3 variant - intel haswell (2013) and newer
          # - x86-64-v2 ## intel nehalem (2008) and newer
          # - x86-64-v3 ## intel haswell (2013) and newer
          # - x86-64-v4 ## intel skylake (2017) and newer
        os:
            - ubuntu-latest
            - macos-latest-large # this is a paid runner apparently
        exclude:
        ############################################
        # exclude linux-musl on macos
          - arch: linux-musl
            os: macos-latest-large
        # exclude linux-glibc on macos
          - arch: linux-glibc
            os: macos-latest-large
        ############################################
        # excludes macos on ubuntu
          - arch: macos
            os: ubuntu-latest
        # excludes windows on macos
          - arch: windows
            os: macos-latest-large
        # excludes windows-arm64
          - arch: windows
            cpu: arm64
        # excludes macos-x64
          - arch: macos
            cpu: x86-64
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      ## Set target env var based on the type of arch build
      - name: Set Target Platform
        id: set_target_platform
        shell: bash
        run: |
          case ${{ matrix.cpu }} in
            "x86-64")
              TARGET_CPU="${{ matrix.cpu }}-v3"
              # RUSTFLAGS="${TARGET_CPU:+${RUSTFLAGS} -Ctarget-cpu=${TARGET_CPU}}"
              case ${{ matrix.arch }} in
                "linux-musl")
                  TARGET="x86_64-unknown-linux-musl"
                  ;;
                "linux-glibc")
                  TARGET="x86_64-unknown-linux-gnu"
                  ;;
                "windows")
                  TARGET="x86_64-pc-windows-gnu"
                  ;;
                "*")
                  ;;
              esac
              ;;
            "arm64")
              case ${{ matrix.arch }} in
                "linux-musl")
                  TARGET="aarch64-unknown-linux-musl"
                  ;;
                "linux-glibc")
                  TARGET="aarch64-unknown-linux-gnu"
                  ;;
                "macos")
                  TARGET="aarch64-apple-darwin"
                  ;;
                "*")
                  ;;
              esac
              ;;
            "*")
              ;;
          esac
          if [[ -z "$TARGET" ]]; then
            echo "TARGET Variable is empty";
            exit 1
          fi
          echo "setting TARGET:${TARGET}"
          echo "setting TARGET_CPU: ${TARGET_CPU}"
          echo "TARGET=${TARGET}" >> "$GITHUB_ENV"
          echo "TARGET_CPU=${TARGET_CPU}" >> "$GITHUB_ENV"

        # run: |
        #   case ${{ matrix.arch }} in
        #     "linux-musl")
        #       case ${{ matrix.cpu }} in
        #         "arm64")
        #           # sudo apt-get install -y gcc-aarch64-linux-gnu musl-dev
        #           TARGET="aarch64-unknown-linux-musl"
        #           ;;
        #         "x86-64")
        #           # sudo apt-get install musl-tools
        #           TARGET="x86_64-unknown-linux-musl"
        #           ;;
        #         "*")
        #           ;;
        #       esac
        #       ;;
        #     "linux-glibc")
        #       case ${{ matrix.cpu }} in
        #         "arm64")
        #           # sudo apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm
        #           TARGET="aarch64-unknown-linux-gnu"
        #           ;;
        #         "x86-64")
        #           # sudo apt-get install -y git libclang-dev llvm
        #           TARGET="x86_64-unknown-linux-gnu"
        #           ;;
        #         "*")
        #           ;;
        #       esac
        #       ;;
        #     "macos")
        #       TARGET="aarch64-apple-darwin"
        #       ;;
        #     "windows")
        #       # sudo apt-get install -y git gcc-mingw-w64-x86-64
        #       TARGET="x86_64-pc-windows-gnu"
        #       ;;
        #     "*")
        #       ;;
        #   esac
        #   if [[ -z "$TARGET" ]]; then
        #     echo "TARGET Variable is empty";
        #     exit 1
        #   fi
        #   echo "setting Target:${TARGET}"
        #   echo "TARGET=${TARGET}" >> "$GITHUB_ENV"

      # set target for the toolchain step
      # musl-x64=x86_64-v3
      # musl-aarch64=aarch64-unknown-linux-musl
      # glibc-x64=x86_64-v3
      # glibc-aarch64=aarch64-unknown-linux-gnu
      # windows-x64=x86_64-pc-windows-gnu
      # macos-aarch64=aarch64-apple-darwin

        # echo "DOCKERFILE=Dockerfile.${{ inputs.arch }}-${DOCKERFILE_CPU}" >> "$GITHUB_ENV"
        # echo "ZIPFILE=${{ inputs.arch }}-${ARCHIVE_NAME}" >> "$GITHUB_ENV"
        # echo "TARGET_CPU=${TARGET_CPU}" >> "$GITHUB_ENV"

      # ## cleanup runner
      # - name: Cleanup Runner
      #   id: runner_cleanup
      #   uses: stacks-network/actions/cleanup/disk@main

      ## Checkout the code
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      ## Install rust toolchain (llvm-tools-preview)
      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: stable
          cache: false
          target: ${{ env.TARGET }}

      - name: Setup Musl Cross
        if: |
          env.TARGET == 'aarch64-unknown-linux-musl'
        id: musl_cross
        shell: bash
        run: |
          curl -LSf -# https://github.com/musl-cc/musl.cc/releases/download/v0.0.1/aarch64-linux-musl-cross.tgz | tar zxf - -C /tmp

      # ## Set env vars based on the type of arch build
      # - name: Set local env vars
      #   id: set_env
      #   shell: bash
      #   run: |
      #     case ${{ matrix.cpu }} in
      #       x86-64)
      #         ## default x64 builds to use v3 variant. TARGET_CPU is required to build for v3 via RUSTFLAGS
      #         TARGET_CPU="${{ inputs.cpu }}-v3"
      #         DOCKERFILE_CPU="x64"
      #         ARCHIVE_NAME="x64"
      #         ;;
      #       x86-64-v2)
      #         ## intel nehalem (2008) and newer
      #         TARGET_CPU="${{ inputs.cpu }}"
      #         DOCKERFILE_CPU="x64"
      #         ARCHIVE_NAME="x64-v2"
      #         ;;
      #       x86-64-v3)
      #         ## intel haswell (2013) and newer
      #         TARGET_CPU="${{ inputs.cpu }}"
      #         DOCKERFILE_CPU="x64"
      #         ARCHIVE_NAME="x64-v3"
      #         ;;
      #       x86-64-v4)
      #         ## intel skylake (2017) and newer
      #         TARGET_CPU="${{ inputs.cpu }}"
      #         DOCKERFILE_CPU="x64"
      #         ARCHIVE_NAME="x64-v4"
      #         ;;
      #       *)
      #         TARGET_CPU=""
      #         DOCKERFILE_CPU="${{ inputs.cpu }}"
      #         ARCHIVE_NAME="${{ inputs.cpu }}"
      #         ;;
      #     esac
      #     echo "DOCKERFILE=Dockerfile.${{ inputs.arch }}-${DOCKERFILE_CPU}" >> "$GITHUB_ENV"
      #     echo "ZIPFILE=${{ inputs.arch }}-${ARCHIVE_NAME}" >> "$GITHUB_ENV"
      #     echo "TARGET_CPU=${TARGET_CPU}" >> "$GITHUB_ENV"


      ## echo what we're doing
      - name: Configure Build Environment
        id: configure_build_env
        shell: bash
        run: |
          echo "arch: ${{ matrix.arch }}"
          echo "cpu: ${{ matrix.cpu }}"
          echo "os: ${{ matrix.os }}"
          echo "Target: ${{env.TARGET}}"

          case "$TARGET" in
            "aarch64-unknown-linux-musl") # linux-musl-arm64
              sudo apt-get install -y gcc-aarch64-linux-gnu musl-dev
              #curl -LSf -# https://github.com/musl-cc/musl.cc/releases/download/v0.0.1/aarch64-linux-musl-cross.tgz | tar zxf - -C /tmp
              echo "CC=/tmp/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc" >> $GITHUB_ENV
              ;;
            "x86_64-unknown-linux-musl") # linux-musl-x86_64
              sudo apt-get install musl-tools
              echo "RUSTFLAGS=\"${TARGET_CPU:+${RUSTFLAGS} -Ctarget-cpu=${TARGET_CPU}}\"" >> $GITHUB_ENV
              ;;
            "x86_64-unknown-linux-gnu") # linux-glibc-x86_64
              sudo apt-get install -y git libclang-dev llvm
              echo "RUSTFLAGS=\"${TARGET_CPU:+${RUSTFLAGS} -Ctarget-cpu=${TARGET_CPU}}\"" >> $GITHUB_ENV
              ;;
            "aarch64-unknown-linux-gnu") # linux-glibc-arm64
              sudo apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm
              echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              ;;
            "x86_64-pc-windows-gnu") # windows-x86_64
              sudo apt-get install -y git gcc-mingw-w64-x86-64
              echo "CC_x86_64_pc_windows_gnu=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV
              echo "CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV
              echo "RUSTFLAGS=\"${TARGET_CPU:+${RUSTFLAGS} -Ctarget-cpu=${TARGET_CPU}}\"" >> $GITHUB_ENV
              ;;
            "aarch64-apple-darwin") # macos-arm64
              ;;
            "*")
              echo "Target: $TARGET"
              echo "no match for build target. exiting"
              exit 1
              ;;
          esac
          exit 0

      ## echo what we're doing
      - name: Output Build Environment
        id: output_build_env
        shell: bash
        run: |
          echo "CC: $CC"
          echo "RUSTFLAGS: $RUSTFLAGS"
          echo "CC_aarch64_unknown_linux_gnu: $CC_aarch64_unknown_linux_gnu"
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: $CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER"
          echo "CC_x86_64_pc_windows_gnu: $CC_x86_64_pc_windows_gnu"
          echo "CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: $CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER"
          echo "cargo build --features monitoring_prom,slog_json --profile release-lite --workspace --target $TARGET"

      # - name: Build Binary (${{ matrix.arch }}_${{ matrix.cpu }})
      #   uses: stacks-network/actions/stacks-core/release/create-source-binary@main
      #   with:
      #     arch: ${{ matrix.arch }}
      #     cpu: ${{ matrix.cpu }}
      #     node_tag: ${{ inputs.node_tag }}
      #     signer_tag: ${{ inputs.signer_tag }}
      #     signer_docker_tag: ${{ inputs.signer_docker_tag }}
      #     is_node_release: ${{ inputs.is_node_release }}
