## Github workflow to create reusable caches

name: Build Release Binaries

on:
    workflow_call:
        inputs:
            node_tag:
                description: "Node Release Tag"
                required: true
                type: string
            node_docker_tag:
                description: "Node Docker Release Tag"
                required: true
                type: string
            signer_tag:
                description: "Signer Release Tag"
                required: true
                type: string
            signer_docker_tag:
                description: "Signer Docker Release Tag"
                required: true
                type: string
            is_node_release:
                description: "True if it is a node release"
                required: true
                type: string
            is_signer_release:
                description: "True if it is a signer release"
                required: true
                type: string

concurrency:
    group: release-build-${{ github.head_ref || github.ref }}
    ## Always cancel duplicate jobs
    cancel-in-progress: true

run-name: test release build matrix

env:
    # set a default command to build. we'll define specific build config options later per arch.
    CMD: "cargo build --features monitoring_prom,slog_json --profile release-lite --workspace"
    # ensure these env vars have no values since they will be explicitly set later
    TARGET_CPU: ""
    LINKER: ""
jobs:
    # ## Build arch dependent binaries from source
    # ##
    # ## Runs when the following is true:
    # ##  - either node or signer tag is provided
    # andon-cord:
    #     # if: |
    #     #     inputs.node_tag != '' ||
    #     #     inputs.signer_tag != ''
    #     name: Andon Cord
    #     runs-on: ubuntu-latest
    #     environment: "Build Release"
    #     steps:
    #         - name: Check Approval
    #           id: check
    #           run: |
    #               exit 0

    build-binaries:
        name: Build Binaries
        permissions:
            id-token: write
            attestations: write
        # needs:
        #     - andon-cord
        strategy:
            ## Run a maximum of 10 builds concurrently, using the matrix defined in inputs.arch
            max-parallel: 10
            matrix:
                arch:
                    - linux-glibc
                    # # disabled for testing
                    # - linux-musl
                    # - macos
                    # - windows
                cpu:
                    - x86-64 ## defaults to x86-64-v3 variant - intel haswell (2013) and newer
                    # # disabled for testing
                    # - arm64
                    #
                    ## legacy
                    # - x86-64-v2 ## intel nehalem (2008) and newer
                    # - x86-64-v3 ## intel haswell (2013) and newer
                    # - x86-64-v4 ## intel skylake (2017) and newer
                os:
                    - ubuntu-latest
                    - macos-latest-large # this is a paid runner apparently
                exclude:
                    ############################################
                    # exclude linux-musl on macos
                    - arch: linux-musl
                      os: macos-latest-large
                    # exclude linux-glibc on macos
                    - arch: linux-glibc
                      os: macos-latest-large
                    ############################################
                    # excludes macos on ubuntu
                    - arch: macos
                      os: ubuntu-latest
                    # excludes windows on macos
                    - arch: windows
                      os: macos-latest-large
                    # excludes windows-arm64
                    - arch: windows
                      cpu: arm64
                    # excludes macos-x64
                    - arch: macos
                      cpu: x86-64
                    ##  added for testing
                    # excludes macos-arm64
                    - arch: macos
                      cpu: arm64
        # runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest
        steps:
            # ## cleanup runner
            # - name: Cleanup Runner
            #   id: runner_cleanup
            #   uses: stacks-network/actions/cleanup/disk@main

            ## Checkout the code
            - name: Checkout the latest code
              id: git_checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            ## Set target env var based on the type of arch build
            # ** we could move all later steps here, but it would be messier and and move verbose per arch.
            - name: Configure Target Platform
              id: configure_target_platform
              shell: bash
              run: |
                  case ${{ matrix.cpu }} in
                    x86-64*)
                      # TARGET_CPU="${{ matrix.cpu }}-v3"
                      ARCHIVE_NAME="$(echo "${{matrix.cpu}}" | sed -e 's|86-||g')" # if matrix.cpu ever changes to a different x86 version, this will set the archive naming appropriately.
                      case ${{ matrix.cpu }} in
                        x86-64)
                          TARGET_CPU="${{ matrix.cpu }}-v3" # default to x86-64-v3 if generic x86-64 is used for the build
                          ;;
                        *)
                          TARGET_CPU="${{ matrix.cpu }}" # if matrix.cpu is specifically v3/v4, we should target that
                          ;;
                      esac

                      case ${{ matrix.arch }} in
                        linux-musl)
                          # install dependencies for linux x64 musl and set target
                          sudo apt-get install -y musl-tools || exit 1
                          TARGET="x86_64-unknown-linux-musl"
                          ;;
                        linux-glibc)
                          # install dependencies for linux x64 glibc and set target
                          sudo apt-get install -y git libclang-dev llvm || exit 1
                          TARGET="x86_64-unknown-linux-gnu"
                          ;;
                        windows)
                          # install dependencies for windos x64 glibc and set target
                          sudo apt-get install -y git gcc-mingw-w64-x86-64 || exit 1
                          TARGET="x86_64-pc-windows-gnu"
                          ;;
                        *)
                          ;;
                      esac
                      ;;
                    arm64)
                      ARCHIVE_NAME=${{matrix.cpu}}
                      case ${{ matrix.arch }} in
                        linux-musl)
                          # install dependencies for linux aarch64 musl and set target
                          sudo apt-get install -y gcc-aarch64-linux-gnu musl-dev || exit 1
                          curl -LSf -# https://github.com/musl-cc/musl.cc/releases/download/v0.0.1/aarch64-linux-musl-cross.tgz | tar zxf - -C /tmp || exit 1
                          TARGET="aarch64-unknown-linux-musl"
                          ;;
                        linux-glibc)
                          # install dependencies for linux aarch64 glibc and set target
                          sudo apt-get install -y git gcc-aarch64-linux-gnu libclang-dev llvm || exit 1
                          TARGET="aarch64-unknown-linux-gnu"
                          ;;
                        macos)
                          TARGET="aarch64-apple-darwin"
                          ;;
                        *)
                          ;;
                      esac
                      ;;
                    *)
                      ;;
                  esac
                  if [[ -z "$TARGET" ]]; then
                    echo "[ERROR] TARGET Variable is empty for ${{ matrix.arch }}-${{ matrix.cpu }}";
                    exit 1
                  fi
                  echo "setting TARGET:${TARGET}"
                  echo "setting TARGET_CPU: ${TARGET_CPU}"
                  echo "setting ZIPFILE_NAME: ${{ matrix.arch }}-${ARCHIVE_NAME}"
                  echo "TARGET=${TARGET}" >> "$GITHUB_ENV"
                  echo "TARGET_CPU=${TARGET_CPU}" >> "$GITHUB_ENV"
                  echo "ZIPFILE_NAME=${{matrix.arch}}-${ARCHIVE_NAME}" >> "$GITHUB_ENV"

            ## Install rust toolchain (llvm-tools-preview)
            - name: Setup Rust Toolchain
              id: setup_rust_toolchain
              uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
              with:
                  toolchain: stable
                  cache: false
                  target: ${{ env.TARGET }}

            ## Build the release binaries
            - name: Build Release
              id: build_release
              shell: bash
              run: |
                  echo "arch: ${{ matrix.arch }}"
                  echo "cpu: ${{ matrix.cpu }}"
                  echo "os: ${{ matrix.os }}"
                  echo "TARGET: ${{env.TARGET}}"
                  echo "TARGET_CPU: ${{env.TARGET_CPU}}"
                  echo "CMD: ${{env.CMD}}"
                  echo "ZIPFILE_NAME: ${{env.ZIPFILE_NAME}}"

                  # case "${{env.TARGET}}" in
                  #   # linux glibc aarch64
                  #   aarch64-unknown-linux-gnu) # linux-glibc-arm64
                  #     LINKER=aarch64-linux-gnu-gcc
                  #     echo "$CMD --target $TARGET --config \"target.${TARGET}.linker=\\\"${LINKER}\\\"\" "
                  #     ${{env.CMD}} --target $TARGET --config "target.${{env.TARGET}}.linker=\"${LINKER}\"" || exit 1
                  #     ;;
                  #   # linux glibc x64
                  #   x86_64-unknown-linux-gnu) # linux-glibc-x86_64
                  #      echo "$CMD --target $TARGET --config build.rustflags=\"\\\"-C target-cpu=${TARGET_CPU}\\\"\" "
                  #     ${{env.CMD}} --target $TARGET --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" || exit 1
                  #     ;;
                  #   # windows glibc x64
                  #   x86_64-pc-windows-gnu) # windows-x86_64
                  #     LINKER=x86_64-w64-mingw32-gcc
                  #     echo "$CMD --target $TARGET --config \"target.${TARGET}.linker=\\\"${LINKER}\\\"\"  --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" "
                  #     ${{env.CMD}} --target $TARGET --config "target.${{env.TARGET}}.linker=\"${LINKER}\"" --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" || exit 1
                  #     ;;
                  #   # linux musl x64
                  #   x86_64-unknown-linux-musl) # linux-musl-x86_64
                  #     echo "$CMD --target $TARGET --config build.rustflags=\"\\\"-C target-cpu=${TARGET_CPU}\\\"\" "
                  #     ${{env.CMD}} --target $TARGET --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" || exit 1
                  #     ;;
                  #   # linux musl aarch64
                  #   aarch64-unknown-linux-musl) # linux-musl-arm64
                  #     LINKER=/tmp/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
                  #     echo "$CMD --target $TARGET --config \"target.${TARGET}.linker=\\\"${LINKER}\\\"\" "
                  #     ${{env.CMD}} --target $TARGET --config "target.${{env.TARGET}}.linker=\"${LINKER}\"" || exit 1
                  #     ;;
                  #   # macos aarch64
                  #   aarch64-apple-darwin) # macos-arm64
                  #     TARGET_CPU=native
                  #     echo "$CMD --target $TARGET --config build.rustflags=\"\\\"-C target-cpu=${TARGET_CPU}\\\"\" "
                  #     ${{env.CMD}} --target $TARGET --config build.rustflags="\"-C target-cpu=${TARGET_CPU}\"" || exit 1
                  #     ;;
                  #   # catchall - run default command
                  #   *)
                  #     echo "No matrix match for build target ($TARGET). using defaults"
                  #     ${{env.CMD}} || exit 1
                  #     ;;
                  # esac
                  exit 0

            # ## Compress the binary artifact
            # - name: Compress binaries
            #   id: compress_artifacts
            #   shell: bash
            #   run: |
            #       file -0 ./target/${{env.TARGET}}/release-lite/* | sed -nE 's/\x0:\s*(ELF|PE32+|Mach).*//p' | zip --junk-paths ${{env.ZIPFILE_NAME}}.zip -@

            # ## Upload the binary artifact to the github action (used in `github-release.yml` to create a release)
            # - name: Upload Artifact
            #   id: upload_artifact
            #   uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
            #   with:
            #       name: ${{ inputs.node_tag || inputs.signer_docker_tag }}-binary-build-${{ env.ZIPFILE }}
            #       # name: binaries-${{ env.ZIPFILE_NAME }}
            #       path: ${{ env.ZIPFILE_NAME }}.zip

            # ## Attest the release binaries
            # - name: Attest Release Artifact
            #   uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 #v2.2.3
            #   with:
            #       subject-path: ${{ env.ZIPFILE_NAME }}.zip

    docker-image:
        name: Build Docker Images
        needs:
            # - andon-cord
            - build-binaries
        ## Creates the node docker image
        uses: ./.github/workflows/release-docker.yml
        with:
            node_tag: ${{ inputs.node_tag }}
            node_docker_tag: ${{ inputs.node_docker_tag }}
            signer_tag: ${{ inputs.signer_tag }}
            signer_docker_tag: ${{ inputs.signer_docker_tag }}
            is_node_release: ${{ inputs.is_node_release }}
            is_signer_release: ${{ inputs.is_signer_release }}
