## Github workflow to create reusable caches

name: TEST workflow

on:
  workflow_dispatch:
  workflow_call:

## env vars are transferred to composite action steps
env:
  BTC_VERSION: "27.2"

##
## Cache will exist longer than workflow execution so other runners have access
##   ex: a failed job should have access to the cache for however long `cleanup.yml` is set to delete old caches
##       however, this is only relevant if the commit sha does not change between runs
concurrency:
  group: test-${{ github.head_ref || github.ref || github.run_id}}
  ## Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  rustfmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - name: echo
        id: echo
        shell: bash
        run: |
          echo "github.event.number: ${{ github.event.number }}"
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"
          echo "github.event.issue.number: ${{ github.event.issue.number }}"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "$GITHUB_REF" | awk -F / '{print $3}'

#     default: ${{ github.event.repository.name }}-${{ github.event.pull_request.head.sha || github.sha }}-cargo


      - name: Rust Toolchain
        id: toolchain
        uses: wileyj/actions/rust-toolchain@chore/6107
        with:
          # rust-toolchain: nightly
          component: "rustfmt"
          cache: true

      - name: Rustfmt
        id: rustfmt
        uses: wileyj/actions/rustfmt@chore/6107
        with:
          alias: "fmt-stacks"

  # create-cache:
  #   name: Create Test Cache
  #   needs:
  #     - rustfmt
  #   uses: ./.github/workflows/create-cache.yml

  # check-cache:
  #   name: Check Cache
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cleanup Runner
  #       id: runner_cleanup
  #       uses: stacks-network/actions/cleanup/disk@main

  #     ## Checkout the code
  #     - name: Checkout the latest code
  #       id: git_checkout
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  #     ## Install rust toolchain (llvm-tools-preview)
  #     - name: Setup Rust Toolchain
  #       id: setup_rust_toolchain
  #       uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
  #       with:
  #         toolchain: stable
  #         components: llvm-tools-preview
  #         cache: false

  #     ## Restore cargo cache data
  #     - name: Restore Cargo Cache
  #       id: restore_cargo_cache
  #       uses: stacks-network/actions/stacks-core/cache/cargo@chore/6107
  #       with:
  #         action: restore

  #     ## Restore bitcoin cache data
  #     - name: Restore Bitcoin Binary Cache
  #       id: restore_bitcoin_cache
  #       uses: stacks-network/actions/stacks-core/cache/bitcoin@chore/6107
  #       with:
  #         action: restore
  #         btc-version: ${{ inputs.btc-version }}

  #     ## Symlink bitoind to $PATH
  #     - name: Link Bitcoin Binary
  #       id: bitcoin_binary
  #       shell: bash
  #       run: |
  #         ls -al /tmp
  #         sudo ln -s /tmp/bitcoin/bin/bitcoind /bin/
  #         ls -al /bin/bitcoind
